# Generated by Django 4.2.1 on 2023-11-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkdin',
            field=models.URLField(blank=True),
        ),
    ]
